# Generated by Django 4.2.16 on 2025-11-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_profile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mp_access_token',
            field=models.CharField(blank=True, help_text='MercadoPago access token del vendedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mp_connected_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de conexión con MercadoPago', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mp_public_key',
            field=models.CharField(blank=True, help_text='MercadoPago public key del vendedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mp_refresh_token',
            field=models.CharField(blank=True, help_text='MercadoPago refresh token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mp_user_id',
            field=models.CharField(blank=True, help_text='ID de usuario en MercadoPago', max_length=50, null=True),
        ),
    ]
