# Generated by Django 5.2.5 on 2025-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, default='Generico', max_length=100),
        ),
    ]
