# Generated by Django 4.2.1 on 2025-09-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercado", "0002_product_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
