# Generated by Django 4.2.16 on 2025-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='mercado_prod_created_762148_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='mercado_prod_categor_2a0a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', '-created_at'], name='mercado_prod_seller__70c99f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', '-created_at'], name='mercado_prod_active_937491_idx'),
        ),
    ]
