# Generated by Django 4.2.16 on 2025-11-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa y Accesorios'), ('hogar', 'Hogar y Muebles'), ('deportes', 'Deportes y Fitness'), ('libros', 'Libros y Medios'), ('juguetes', 'Juguetes y Juegos'), ('belleza', 'Belleza y Cuidado Personal'), ('alimentos', 'Alimentos y Bebidas'), ('automotor', 'Automotor'), ('mascotas', 'Mascotas'), ('jardin', 'Jardín y Exterior'), ('oficina', 'Oficina y Papelería'), ('instrumentos', 'Instrumentos Musicales'), ('arte', 'Arte y Manualidades'), ('otros', 'Otros')], default='otros', max_length=200),
        ),
    ]
