# Generated by Django 4.2.16 on 2025-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_add_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vehiculos', 'Vehículos'), ('inmuebles', 'Inmuebles'), ('supermercado', 'Supermercado'), ('tecnologia', 'Tecnología'), ('hogar_muebles', 'Hogar, Muebles y Jardín'), ('electrodomesticos', 'Electrodomésticos'), ('herramientas', 'Herramientas'), ('construccion', 'Construcción'), ('deportes_fitness', 'Deportes y Fitness'), ('accesorios_vehiculos', 'Accesorios para Vehículos'), ('moda', 'Moda'), ('belleza', 'Belleza y Cuidado Personal'), ('salud', 'Salud y Equipamiento Médico'), ('juguetes', 'Juguetes y Juegos'), ('bebes', 'Bebés'), ('mascotas', 'Animales y Mascotas'), ('libros', 'Libros, Revistas y Comics'), ('musica_peliculas', 'Música, Películas y Series'), ('instrumentos_musicales', 'Instrumentos Musicales'), ('consolas_videojuegos', 'Consolas y Videojuegos'), ('camaras_accesorios', 'Cámaras y Accesorios'), ('celulares_telefonia', 'Celulares y Telefonía'), ('computacion', 'Computación'), ('tablets_accesorios', 'Tablets y Accesorios'), ('televisores', 'Televisores'), ('audio', 'Audio'), ('componentes_electronicos', 'Componentes Electrónicos'), ('industrias_oficinas', 'Industrias y Oficinas'), ('agro', 'Agro'), ('arte_libreria', 'Arte, Librería y Mercería'), ('antiguedades', 'Antigüedades y Colecciones'), ('souvenirs', 'Souvenirs, Cotillón y Fiestas'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='otros', max_length=200),
        ),
    ]
