# Generated by Django 4.2.16 on 2025-11-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_expand_categories_ml'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='mercado_pro_created_0099bc_idx',
            old_name='mercado_prod_created_762148_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='mercado_pro_categor_053527_idx',
            old_name='mercado_prod_categor_2a0a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='mercado_pro_seller__f0c3c8_idx',
            old_name='mercado_prod_seller__70c99f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='mercado_pro_active_02137d_idx',
            old_name='mercado_prod_active_937491_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
