# Generated by Django 4.2.16 on 2025-11-07 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0011_rename_mercado_prod_created_762148_idx_mercado_pro_created_0099bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='mercado_pro_title_11a94e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['marca'], name='mercado_pro_marca_3f1eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'stock'], name='mercado_pro_active_583586_idx'),
        ),
    ]
