# Generated by Django 5.2.7 on 2025-11-07 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0012_cart_created_at_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/additional/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0 = primera)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mercado.product')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['product', 'order'], name='mercado_pro_product_020b69_idx')],
            },
        ),
    ]
