# Generated by Django 5.2.7 on 2025-11-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0002_directmessagethread_directmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blocker'], name='chat_intern_blocker_3249a4_idx'), models.Index(fields=['blocked'], name='chat_intern_blocked_42d16c_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair')],
            },
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('declined', 'Rechazada')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['requester'], name='chat_intern_request_89c7c6_idx'), models.Index(fields=['target'], name='chat_intern_target__4713e3_idx'), models.Index(fields=['status'], name='chat_intern_status_3cebe8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'requested')), fields=('requester', 'target'), name='unique_pending_chat_request')],
            },
        ),
    ]
