# Generated by Django 5.2.7 on 2025-11-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_sale', 'Nueva venta'), ('new_follower', 'Nuevo seguidor'), ('new_product', 'Nuevo producto'), ('product_sold_out', 'Producto agotado'), ('low_stock', 'Stock bajo'), ('chat_request', 'Solicitud de chat'), ('chat_accepted', 'Chat aceptado')], max_length=30),
        ),
    ]
